// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwwzpvqhxqdmytjlitah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3d3pwdnFoeHFkbXl0amxpdGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MTk2NTMsImV4cCI6MjA1OTM5NTY1M30.QXEFqIIvjr_H8E-qsPa3XKFAYeoenngWbBMFhFFjBPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);